### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
# code

import numpy as np

a = np.random.randint(1 , 100 , 15)

a


array([23, 46, 48, 47, 48, 85, 19, 95,  5, 12, 18, 71, 31, 71, 63])

In [5]:
b = np.random.randint(1 , 100 , 24).reshape(6 , 4)

b

array([[ 8, 37,  1, 10],
       [82,  3, 14, 87],
       [30, 40, 86, 34],
       [20, 49, 89, 18],
       [11, 59, 44, 38],
       [34, 37, 66,  2]])

In [9]:
np.sort(a)

array([ 5, 12, 18, 19, 23, 31, 46, 47, 48, 48, 63, 71, 71, 85, 95])

In [11]:
np.sort(b , axis = 0) 

# when the axis is 0  then sorting is column based

array([[ 8,  3,  1,  2],
       [11, 37, 14, 10],
       [20, 37, 44, 18],
       [30, 40, 66, 34],
       [34, 49, 86, 38],
       [82, 59, 89, 87]])

In [12]:
np.sort(b , axis = -1)

# when the axis is 0  then sorting is row based

array([[ 1,  8, 10, 37],
       [ 3, 14, 82, 87],
       [30, 34, 40, 86],
       [18, 20, 49, 89],
       [11, 38, 44, 59],
       [ 2, 34, 37, 66]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [13]:
# code

np.append(a , 200)



array([ 23,  46,  48,  47,  48,  85,  19,  95,   5,  12,  18,  71,  31,
        71,  63, 200])

In [15]:
b

np.append(b , np.ones((b.shape[0] , 1)) , axis = 1)

# addes the column in the last

array([[ 8., 37.,  1., 10.,  1.],
       [82.,  3., 14., 87.,  1.],
       [30., 40., 86., 34.,  1.],
       [20., 49., 89., 18.,  1.],
       [11., 59., 44., 38.,  1.],
       [34., 37., 66.,  2.,  1.]])

In [17]:
np.append(b , np.random.random((b.shape[0] , 1)) , axis = 1)

array([[ 8.        , 37.        ,  1.        , 10.        ,  0.8567539 ],
       [82.        ,  3.        , 14.        , 87.        ,  0.79033781],
       [30.        , 40.        , 86.        , 34.        ,  0.30326666],
       [20.        , 49.        , 89.        , 18.        ,  0.16186457],
       [11.        , 59.        , 44.        , 38.        ,  0.42520938],
       [34.        , 37.        , 66.        ,  2.        ,  0.78986259]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [18]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [20]:
np.concatenate((c , d) , axis = 0)

# concatenation row wise


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.concatenate((c , d) , axis=1)

# concatenation column wise



array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [22]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [23]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [24]:
# expanded dimension
# 1d array --> 2d array
# 2d array ---> 3d array 
# 3d array ---> 4d array

# using exapnd_dims function

a



array([23, 46, 48, 47, 48, 85, 19, 95,  5, 12, 18, 71, 31, 71, 63])

In [26]:
np.expand_dims(a , axis = 0)

array([[23, 46, 48, 47, 48, 85, 19, 95,  5, 12, 18, 71, 31, 71, 63]])

In [28]:
np.expand_dims(a , axis = 0).shape

(1, 15)

In [27]:
np.expand_dims(a , axis = 1)

array([[23],
       [46],
       [48],
       [47],
       [48],
       [85],
       [19],
       [95],
       [ 5],
       [12],
       [18],
       [71],
       [31],
       [71],
       [63]])

In [29]:
np.expand_dims(a , axis = 1).shape

(15, 1)