### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code

import numpy as np

a = np.random.randint(1 , 100 , 15)

a


array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [3]:
b = np.random.randint(1 , 100 , 24).reshape(6 , 4)

b

array([[84, 67, 70, 20],
       [45, 77, 29, 19],
       [94, 60, 92, 89],
       [78, 55, 53,  2],
       [77,  2, 97, 50],
       [15, 26, 65, 36]])

In [4]:
np.sort(a)

array([ 3,  8, 22, 25, 25, 27, 46, 49, 56, 57, 63, 88, 88, 94, 98])

In [5]:
np.sort(b , axis = 0) 

# when the axis is 0  then sorting is column based

array([[15,  2, 29,  2],
       [45, 26, 53, 19],
       [77, 55, 65, 20],
       [78, 60, 70, 36],
       [84, 67, 92, 50],
       [94, 77, 97, 89]])

In [6]:
np.sort(b , axis = -1)

# when the axis is 0  then sorting is row based

array([[20, 67, 70, 84],
       [19, 29, 45, 77],
       [60, 89, 92, 94],
       [ 2, 53, 55, 78],
       [ 2, 50, 77, 97],
       [15, 26, 36, 65]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
# code

np.append(a , 200)



array([ 88,   3,  25,  25,  49,  98,  57,  94,  22,  56,   8,  46,  27,
        88,  63, 200])

In [8]:
b

np.append(b , np.ones((b.shape[0] , 1)) , axis = 1)

# addes the column in the last

array([[84., 67., 70., 20.,  1.],
       [45., 77., 29., 19.,  1.],
       [94., 60., 92., 89.,  1.],
       [78., 55., 53.,  2.,  1.],
       [77.,  2., 97., 50.,  1.],
       [15., 26., 65., 36.,  1.]])

In [9]:
np.append(b , np.random.random((b.shape[0] , 1)) , axis = 1)

array([[8.40000000e+01, 6.70000000e+01, 7.00000000e+01, 2.00000000e+01,
        2.15182228e-01],
       [4.50000000e+01, 7.70000000e+01, 2.90000000e+01, 1.90000000e+01,
        3.09108785e-01],
       [9.40000000e+01, 6.00000000e+01, 9.20000000e+01, 8.90000000e+01,
        9.98437229e-02],
       [7.80000000e+01, 5.50000000e+01, 5.30000000e+01, 2.00000000e+00,
        2.36876753e-01],
       [7.70000000e+01, 2.00000000e+00, 9.70000000e+01, 5.00000000e+01,
        2.43791936e-03],
       [1.50000000e+01, 2.60000000e+01, 6.50000000e+01, 3.60000000e+01,
        9.18950108e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c , d) , axis = 0)

# concatenation row wise


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c , d) , axis=1)

# concatenation column wise



array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
# expanded dimension
# 1d array --> 2d array
# 2d array ---> 3d array 
# 3d array ---> 4d array

# using exapnd_dims function

a



array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [16]:
np.expand_dims(a , axis = 0)

array([[88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63]])

In [17]:
np.expand_dims(a , axis = 0).shape

(1, 15)

In [18]:
np.expand_dims(a , axis = 1)

array([[88],
       [ 3],
       [25],
       [25],
       [49],
       [98],
       [57],
       [94],
       [22],
       [56],
       [ 8],
       [46],
       [27],
       [88],
       [63]])

In [19]:
np.expand_dims(a , axis = 1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [20]:
a 

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [21]:
# find all indices with value greater than 50

np.where(a > 50)

# np.where function finds the index of the given elements based on the condition or situation

(array([ 0,  5,  6,  7,  9, 13, 14], dtype=int64),)

In [22]:
# replace all values > 50 with 0

np.where(a > 50 , 0 , a)


# np.where(condition , true , false)
# this is the syntax
# first one is condition where you give the condition
# 2nd is true means when the condtion is get true then we have to do we give there
# 3rd one is the false means when the cion===

array([ 0,  3, 25, 25, 49,  0,  0,  0, 22,  0,  8, 46, 27,  0,  0])

In [23]:
# replace all the numbers which are even with 0

np.where(a % 2 == 0 , 0 , a)

array([ 0,  3, 25, 25, 49,  0, 57,  0,  0,  0,  0,  0, 27,  0, 63])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [24]:
# the argmax finds the index of the maximum element present in on the given axis 

a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [25]:
np.argmax(a)

5

In [26]:
b

array([[84, 67, 70, 20],
       [45, 77, 29, 19],
       [94, 60, 92, 89],
       [78, 55, 53,  2],
       [77,  2, 97, 50],
       [15, 26, 65, 36]])

In [27]:
np.argmax(b , axis = 0)

# columnwise

array([2, 1, 4, 2], dtype=int64)

In [28]:
np.argmax(b , axis = 1)

# rowwise

array([0, 1, 0, 0, 2, 2], dtype=int64)

###  np.argmin

-       this function is equally opposite of the np.argmax
-       argmax gives the max 
-       argmin gives the min

In [29]:
a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [30]:
np.argmin(a)

1

In [31]:
b

array([[84, 67, 70, 20],
       [45, 77, 29, 19],
       [94, 60, 92, 89],
       [78, 55, 53,  2],
       [77,  2, 97, 50],
       [15, 26, 65, 36]])

In [32]:
np.argmin(b , axis = 0)

array([5, 4, 1, 3], dtype=int64)

In [33]:
np.argmin(b , axis = 1)

array([3, 3, 1, 3, 1, 0], dtype=int64)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [34]:
# this function is used to find the cumulative sum

a

# cumulative sum

# 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9
# 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9
# 1 -> 3 -> 6 -> 10 -> 15 -> 21 -> 28 -> 36 -> 45  -----> this is the cumulative sum



array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [35]:
np.cumsum(a)

array([ 88,  91, 116, 141, 190, 288, 345, 439, 461, 517, 525, 571, 598,
       686, 749])

In [36]:
b

array([[84, 67, 70, 20],
       [45, 77, 29, 19],
       [94, 60, 92, 89],
       [78, 55, 53,  2],
       [77,  2, 97, 50],
       [15, 26, 65, 36]])

In [37]:
np.cumsum(b)

# if we didnt specify axis in case of 2d array then it will convert it in to the 1d array and after conversion it perform the cumsum function on that converted 1d array

array([  84,  151,  221,  241,  286,  363,  392,  411,  505,  565,  657,
        746,  824,  879,  932,  934, 1011, 1013, 1110, 1160, 1175, 1201,
       1266, 1302])

In [38]:
np.cumsum(b , axis = 0)

# column wise

array([[ 84,  67,  70,  20],
       [129, 144,  99,  39],
       [223, 204, 191, 128],
       [301, 259, 244, 130],
       [378, 261, 341, 180],
       [393, 287, 406, 216]])

In [39]:
np.cumsum(b , axis = 1)

# row wise

array([[ 84, 151, 221, 241],
       [ 45, 122, 151, 170],
       [ 94, 154, 246, 335],
       [ 78, 133, 186, 188],
       [ 77,  79, 176, 226],
       [ 15,  41, 106, 142]])

### np.cumprod()

        it is same like cumsum function but it not do sum it will multiply and give the product

In [40]:
a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [41]:
np.cumprod(a)

array([         88,         264,        6600,      165000,     8085000,
         792330000, -2081830256,  1876451552, -1667738816,  1095906816,
         177319936,  -433217536,  1188028416,  1467285504, -2050293760])

In [42]:
np.cumproduct(a)

array([         88,         264,        6600,      165000,     8085000,
         792330000, -2081830256,  1876451552, -1667738816,  1095906816,
         177319936,  -433217536,  1188028416,  1467285504, -2050293760])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [43]:
np.percentile(a , 100)

# 100 th percentile means ---> max number

98.0

In [44]:
np.percentile(a , 0)

# 0 th percentile means ---> min number

3.0

In [45]:
np.percentile(a , 50)

# 50 th percentile means median

49.0

In [46]:
np.median(a)

49.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [47]:
a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [48]:
np.histogram(a)

(array([2, 0, 4, 0, 2, 2, 1, 0, 2, 2], dtype=int64),
 array([ 3. , 12.5, 22. , 31.5, 41. , 50.5, 60. , 69.5, 79. , 88.5, 98. ]))

In [49]:
np.histogram(a , bins= [0 , 10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90 , 100])

(array([2, 0, 4, 0, 2, 2, 1, 0, 2, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [50]:
np.histogram(a , bins=[0 , 50 , 100] )

(array([8, 7], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [51]:
a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [52]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [53]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,5])

np.corrcoef(salary,experience)

array([[1.        , 0.91381155],
       [0.91381155, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [54]:
# np.isin() -->  function is used to check or find the mulitple elements are present in the given array or not

a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [55]:
items = [10 , 20 , 30 , 40 , 50 , 63 , 60 , 70]

np.isin(a , items)



array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [56]:
a[np.isin(a , items)]

array([63])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [57]:
# it reverse the given array

a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [58]:
np.flip(a)

array([63, 88, 27, 46,  8, 56, 22, 94, 57, 98, 49, 25, 25,  3, 88])

In [59]:
b

array([[84, 67, 70, 20],
       [45, 77, 29, 19],
       [94, 60, 92, 89],
       [78, 55, 53,  2],
       [77,  2, 97, 50],
       [15, 26, 65, 36]])

In [60]:
np.flip(b)

# flippling on 2d array is working like 
# firstly the columns are flip
# and then the flip column are again flip in row

array([[36, 65, 26, 15],
       [50, 97,  2, 77],
       [ 2, 53, 55, 78],
       [89, 92, 60, 94],
       [19, 29, 77, 45],
       [20, 70, 67, 84]])

In [61]:
np.flip(b , axis= 0)

# column wise

array([[15, 26, 65, 36],
       [77,  2, 97, 50],
       [78, 55, 53,  2],
       [94, 60, 92, 89],
       [45, 77, 29, 19],
       [84, 67, 70, 20]])

In [62]:
np.flip(b , axis=1)

# row wise

array([[20, 70, 67, 84],
       [19, 29, 77, 45],
       [89, 92, 60, 94],
       [ 2, 53, 55, 78],
       [50, 97,  2, 77],
       [36, 65, 26, 15]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [63]:


a

array([88,  3, 25, 25, 49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

In [64]:
# put 630 on the positio of 63 and 650 on 65

np.put(a , [0 , 1] , [630 , 650])

# this function makes permanent changes in the array
# because of that we cant see the output

In [65]:
a

array([630, 650,  25,  25,  49,  98,  57,  94,  22,  56,   8,  46,  27,
        88,  63])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [66]:
a

array([630, 650,  25,  25,  49,  98,  57,  94,  22,  56,   8,  46,  27,
        88,  63])

In [67]:
# delete 630 from array
# it is used to delete given items from the given array
np.delete(a , 0)

array([650,  25,  25,  49,  98,  57,  94,  22,  56,   8,  46,  27,  88,
        63])

In [68]:
a

array([630, 650,  25,  25,  49,  98,  57,  94,  22,  56,   8,  46,  27,
        88,  63])

In [69]:
# delete multiple items

np.delete(a , [0 , 1 , 2 , 3])

array([49, 98, 57, 94, 22, 56,  8, 46, 27, 88, 63])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [70]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])



In [71]:
np.union1d(m,n)

# this are all the operations that we perform on the sets

# it is used to find the union

array([1, 2, 3, 4, 5, 6, 7])

In [72]:
np.intersect1d(m , n)

# it gives all the elements that are intersect 

array([3, 4, 5])

In [73]:
np.setdiff1d(m , n)

# it shows all the elements that are present in m but not present in n

array([1, 2])

In [75]:
np.setxor1d(m , n)

# it remove the common elements from the both array and give only the not common elements

array([1, 2, 6, 7])

In [77]:
np.in1d(m  , 1)

array([ True, False, False, False, False])

In [78]:
np.in1d(m  , n)

array([False, False,  True,  True,  True])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [79]:
a

array([630, 650,  25,  25,  49,  98,  57,  94,  22,  56,   8,  46,  27,
        88,  63])

In [80]:
np.clip(a , a_min = 25 , a_max = 75)

array([75, 75, 25, 25, 49, 75, 57, 75, 25, 56, 25, 46, 27, 75, 63])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:
# 25. np.allclose and equals