### What is numpy?

        NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


        At the core of the NumPy package, is the `ndarray` object. This encapsulates n-dimensional arrays of homogeneous data types

        numpy is a scientific computational library and the most important thing of numpy is numpy array.
        and using that array the various object are made in this library like matrices , mask arrays , structured arrays.
        using numpy we can perform operations on this objects.(matrices , mask arrays , structured arrays)

        numpy is a mathematical library.


Why we need Numpy?

### Numpy Arrays Vs Python Sequences

- `NumPy arrays` have a `fixed size at creation`, unlike Python lists (which can grow dynamically). `Changing the size of an ndarray` will create a `new array` and `delete the original`.

- The `elements in a NumPy array` are `all required to be of the same data type`, and thus will be the `same size in memory`.

- in python `list we can add data of diffrent data types` but in the `numpy ndArray` we `cannot add the data of the diffrent datatypes` (it is homogenous).

-  `NumPy arrays facilitate advanced mathematical and other types of operations` on `large numbers of data`. Typically, such `operations are executed more efficiently` and with `less code` than is possible using `Python’s built-in sequences(list)`.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

why the numpy library is made ? 

-       because the data types of the python are very slow to perform operations on the huge data set

-       but everyone likes python because syntax of the python is very easy to understand and anyone can learn the python very easily and fastly.

-       to solve the problem of python is very slow and people wants python

-       the numpy is developed.

-       after the developement of numpy the python become the number one choice for the data science and machine learning across the world

-       So the numpy become the godfather of the data science and machine learning which can make the python that much powerfull 

### Creating a Numpy Array

In [3]:
# create a new numpy array

# import the numpy library

import numpy as np

# we give short form to the numpy as 'np'
# we can also another name also

# creating array

np.array([1 , 2 , 3 ])

# our array is created


#store the array in the new variable

a = np.array([1 , 2 , 3 ])

print(a)
print(type(a))

# [1 2 3]  -- > we can called it as a  vector

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2d and 3d numpy array

b = np.array(([[1 , 2 , 3] , [4 , 5 , 6]]))
print(b)

# we make the 2d array
# we can called it as a matrix also because it looks like it 
# in the rows and columns

[[1 2 3]
 [4 5 6]]


[1 2 3]  -- > we can called it as a  vector

[[1 2 3]   
 [4 5 6]]     ---> we make the 2d array
                we can called it as a matrix also because it looks like it 
                in the rows and columns

In [4]:
# 3d numpy array

c = np.array([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7 , 8]]])
print(c)

# we can called 3d numpy arrays as tensor 

# we can make 4d and 5d arrays also
# there is no any restriction.


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### `create a nd Array of our own choice dataType`

In [9]:
# above arrays are integer data type of arrays

# here we can create a array of float 

a = np.array([1 , 2 , 3] , dtype=float)
print(a)

# create array with boolean

b = np.array([0 , 1  , 2  , 3] , dtype = bool)
print(b)
# python consider 0 --> false and 1 ---> true

[1. 2. 3.]
[False  True  True  True]


In [11]:
# np.arange

# this function also creates the numpy array

# this funtion is like range function in python

a = np.arange(1 , 11)
print(a)

# we can also apply slicing here 

a = np.arange(1 , 11 , 2)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [21]:
# with reshape  

# it con convert the given numpy array in to the another array.

a = np.arange(1 , 11).reshape(5 , 2)

print(a)

# using reshape we can convert the given array in to the matrix

print("----------------------------------------------")

a = np.arange(1 , 11).reshape(2 , 5)

print(a)

print("----------------------------------------------")

a = np.arange(1 , 13).reshape(3 , 4)

print(a)

print("----------------------------------------------")

a = np.arange(1 , 13).reshape(4 , 3)

print(a)

print("----------------------------------------------")

a = np.arange(1 , 13).reshape(2 , 6)

print(a)

print("----------------------------------------------")

a = np.arange(1 , 13).reshape(6 , 2)

print(a)

print("----------------------------------------------")

# this will work only in the possible condition other wise it gives error



[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
----------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------------------------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
----------------------------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
----------------------------------------------


In [29]:
# np.ones and np.zeros

# np.ones --> using it we can make an array which all the elements are the 1
# we have to provide a tuple inside the function

a = np.ones((3 , 4))
print(a)


# where we can use it 
# we use it to initialise the array with 1 
# it uses it neural networking , deep learning.


# np.zeros --> here all the elements of the array are zero.

a = np.zeros((3 , 4))
print(a)


# np.ones and np.zeros are used to initialise the arrays or matrix


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
# generate a array or matrix with a rondom number

np.random.random((3 , 4))

array([[0.84111756, 0.879462  , 0.72879089, 0.93909335],
       [0.4123904 , 0.74875754, 0.00160884, 0.13027931],
       [0.64508594, 0.39424527, 0.02604421, 0.42232994]])

In [39]:
# np.linspace

print(np.linspace(-10 , 10 , 10))

# the linspace function 
# is used to generate the random number from the given range 
# and we can tell the function how many numbers we want to generate
# it generate the points on the equal distance
# the diffrence between two points is equal


# 1st -10 is the lower range
# 2nd 10 is the higher range
# 3rd 10 is the number of elements we want to generate

print(np.linspace(-10 , 10 , 10 , dtype= int))

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[-10  -8  -6  -4  -2   1   3   5   7  10]


In [40]:
# np.identity

# using np.identity function we can make the indentity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`by default elements of the numpy arrays are float`

### `Array Attributes`

In [4]:
a1 = np.arange(10)
a2 = np.arange(12 , dtype = float ).reshape(3 , 4)
a3 = np.arange(8).reshape(2 , 2 , 2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
# ndim

# using ndim function we can get the dimension of the array.

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [12]:
# shape

# using shape function we can know how many elements in one direction

a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [19]:
# size
# size attribute is used to check how many items or elements in the given object

print(a3.size)

print(a2.size)




8
12


In [17]:
# itemsize 

# using itemsize we can get how many memory a object stored in the memory

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [18]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int32


### `changing Datatype`

In [23]:
# astype

# using astype we can change the data type of the premade numpy array

print(a3.dtype)

a4 = a3.astype(np.int64)

print(a4.dtype)


int32
int64


### **`Array Operations`** 

In [26]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
# scalar operations 

# scalar operations means we perform operation on the single array

# arithmatic

print(a1 + 2 )

print(a1 - 2 )

print(a1 * 2 )

print(a1 / 2 )

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [32]:
# relational operation

print(a2 > 5)

print("-------------------------------")
# it compare every element of the array

print(a2 > 25)

print("-------------------------------")

print(a2 == 15)

print("-------------------------------")

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
-------------------------------
[[False False False False]
 [False False False False]
 [False False False False]]
-------------------------------
[[False False False  True]
 [False False False False]
 [False False False False]]
-------------------------------


In [35]:
#vector operation

# vector operation means we do operation on the 2 arrays

# arithmatic

print(a1 + a2)

print("-------------------------------")

print(a1 - a2)

print("-------------------------------")

print(a1 * a2)

print("-------------------------------")

print(a1 / a2)

print("-------------------------------")

print(a1 ** a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
-------------------------------
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
-------------------------------
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
-------------------------------
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
-------------------------------
[[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]


##### `if the shapes of the array are same only then the arithmatic operations will work`

### **`Array Functions`**

there are lot of functions in the numpy 

we dont need to code anything while we using numpy

because there are lots of prebuilt functions in the numpy library

In [49]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)


print(a1)



[[16. 89. 79.]
 [40. 36. 46.]
 [ 1. 77. 16.]]


In [54]:
# max
# max function is used to find the maximum element from the given array

print(np.max(a1))

# min  

print(np.min(a1))

# sum 
# sum function gives the sum of all the array elements

print(np.sum(a1))


# prod

# product function gives the multiplication of all the given elements

print(np.prod(a1))

89.0
1.0
400.0
9180537569280.0


In [57]:
# how to find min from the each row of the array

# columnwise
print(np.min(a1 , axis = 0))

# here
# 0 -- > column
# 1 --> row

# row wise
print(np.min(a1 , axis = 1))

# also we can perform other all operations like these

[ 1. 36. 16.]
[16. 36.  1.]


In [60]:
# mean
# it calculate the mean from the given matrix or array
print(np.mean(a1))


# column wise 

print(np.mean(a1 , axis = 0))


# rowwise

print(np.mean(a1 , axis = 1))

44.44444444444444
[19.         67.33333333 47.        ]
[61.33333333 40.66666667 31.33333333]


In [61]:
# median

# finds the mid element or median of the array or matrix

print(np.median(a1))

40.0


In [62]:
# std --> standar deviation

# it gives the standard deviation of the array 

print(np.std(a1))

29.511244979616052


In [63]:
# var  -->  variance

print(np.var(a1))

870.9135802469136


In [65]:
# trigonometric operations

print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[-0.28790332  0.86006941 -0.44411267]
 [ 0.74511316 -0.99177885  0.90178835]
 [ 0.84147098  0.99952016 -0.28790332]]
[[-0.95765948  0.51017704 -0.89597095]
 [-0.66693806 -0.12796369 -0.43217794]
 [ 0.54030231 -0.03097503 -0.95765948]]
[[  0.30063224   1.68582537   0.49567753]
 [ -1.11721493   7.75047091  -2.08661353]
 [  1.55740772 -32.26857578   0.30063224]]


In [67]:
# dot product

# dot product function is used to find the dot product between the 2 matrix

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)


# for dot product the row of the 1st matrrix is equal to column of the 2nd matrix .
# and column of the 1st matrix is equal to the row of the 2nd column

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [69]:
# log and exponents

# using log funtion we can calculate the log of the every element 

print(np.log(a1))

#  exp  --> exponent

# using exp funtion we can calculate the exponent of the every element 

print(np.exp(a1))

[[2.77258872 4.48863637 4.36944785]
 [3.68887945 3.58351894 3.8286414 ]
 [0.         4.34380542 2.77258872]]
[[8.88611052e+06 4.48961282e+38 2.03828107e+34]
 [2.35385267e+17 4.31123155e+15 9.49611942e+19]
 [2.71828183e+00 2.75851345e+33 8.88611052e+06]]


In [77]:
# round / floor / ceil


# round function is used to round up the nearest values

print(np.round(np.random.random((2 , 3)) * 100))

# floor --> floor used the last values to round up

print(np.floor(np.random.random((2 , 3)) * 100))


# ceil --> ceil function push or through to next item

# if 6.1 --> output --> 7

print(np.ceil(np.random.random((2 , 3)) * 100))

[[35. 30. 39.]
 [88.  1. 66.]]
[[ 4. 72.  0.]
 [86. 77. 99.]]
[[58. 61. 99.]
 [13. 46.  4.]]


### **`indexing and Slicing`**

In [79]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [82]:
print(a1)

print(a1[-1])

print(a1[1])

[0 1 2 3 4 5 6 7 8 9]
9
1


In [89]:
print(a2)

print(a2[1 , 2]) # --> to find 6 

# print(a2[1 , 2]) 
# here the 1 is row and 2 is the column in which the 6 is ther in array

# --> 11

print(a2[2 , 3])
print(a2[-1 , -1])

# --> 5

print(a2[1 , 1])
print(a2[-2 , 1])
print(a2[-2 , -3])

# first told which is row and then tell which column inside the bracket



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11
11
5
5
5


In [93]:
# 3d

print(a3)

# --> 5

print(a3[1 , 0 , 1])

# here the 1st 1 is for --> in which 2d array the 5 is there
# again in in which row the 5 is there
# and after that in which column the five is there

# --> 3

print(a3[0 , 1 , 1])

# --> 0

print(a3[0 , 0 , 0])




[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
3
0


In [95]:
print(a1)

# slicing
# --> 234

print(a1[2 : 5])



[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [125]:
print(a2)

print(a2[0 , :])

# 3rd column

print(a2[: , 2])

# find 5 , 6 , 9 , 10

print(a2[1 : , 1 : 3])

# find 0 , 3 , 8 , 11

print(a2[::2 , ::3 ])

# find 1 , 3  , 9 , 11

print(a2[::2 , 1::2])

# find we want which row and which column


# find 4 7 

print(a2[1, 0::3])

# find 1 , 2 , 3 , 5 , 6 , 7

print(a2[0:2 , 1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [131]:
# 3d

a3 = np.arange(27).reshape(3 , 3 , 3)
print(a3)

# find
#   [[ 9 10 11]
#    [12 13 14]
#    [15 16 17]]

print(a3[1])







[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [132]:
# find 1st and last array only

print(a3[0 : : 2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [134]:
# print the 1st arrays 2nd row

print(a3[0 , 1])
print(a3[0 , 1 , :])

[3 4 5]
[3 4 5]


In [135]:
# print 2nd arrays middle column

print(a3[1 , : , 1])

[10 13 16]


In [136]:
# find
# 22 23
# 25 26

print(a3[2 , 1: , 1:])

[[22 23]
 [25 26]]


In [139]:
# find 
# 0 2
# 18 20

print(a3[0::2 , 0:1 , 0::2])

print(a3[::2 , 0 , ::2])

[[[ 0  2]]

 [[18 20]]]
[[ 0  2]
 [18 20]]


### **`Iterating`** 

        if we want we can run loop on our numpy array

In [143]:
print(a1)

for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [145]:
print(a2)

for i in a2 :
    print(i)

# when we apply loop on 2d array then it will print one row at time

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [148]:
#print(a3)

for i in a3 :
    print(i)

# when we run loop on 3d array then it will print one 2d array at time

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [150]:
for i in np.nditer(a3):
    print(i , end=" ")

# if we want to iterate through all elements of the 3 d and 2 d array then ther is a function called np.iter() using this function we can iterate evry element of the array.



0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

### **`reshaping`**

In [ ]:
# reshape

In [154]:
# Transpose
# e.g --> convert 4*3 matrix to 3*4 matrix --> transpose

print(a2)

print(np.transpose(a2))

a2.T  # this is shortcut to use the transpose matrix

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [156]:
# ravel 
# convert n dimensional array to 1 d array

print(a2)
print(a2.ravel())


print(a3)
print(a3.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### **`Stacking`**


        in both stacking and splitting we make changes in our existing array

        in stacking if we want we can join or stackup 2 arrays

        and there are two ways to join : 

                1. horizontal stacking : 

                [2 * 2] [2 * 2]  --> stack 

                --> output --> [2 * 4]

                2. vertical stacking

                [2 * 2] [2 * 2]  --> stack 

                --> output --> [4 * 2]


        we can do stacking on multiple arrrays

In [160]:
# horizontal stacking

a4 = np.arange(12).reshape(3 , 4)

a5 = np.arange(12 , 24).reshape(3 , 4)

print(a4 , a5 , sep = "\n\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [161]:
np.hstack((a4 , a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [163]:
np.hstack((a4 , a5 , a4 , a5 ))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [162]:
# vertical stacking

np.vstack((a4 , a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [164]:
np.vstack((a4 , a5 , a4 , a5 ))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# there was only one requirement of stacking the shape of the all matrix must be same 

### **`splitting`**

        in splitting we seprate the array

        it works opposite of the stacking


        [    |    ]
        [    |    ]   --->>>> horizontal splitting --> breaks  --> horizontally
        [    |    ]
        [    |    ]



        [               ]
        [               ]
          --------------    -->>> vertical splitting --> breaks -->vertically
        [               ]
        [               ]

In [165]:
# horizontal splitting

print(a4)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [166]:
np.hsplit(a4 , 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [168]:
np.hsplit(a4 , 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting



In [170]:
np.vsplit(a4 , 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [172]:
a6 = np.vstack((a4 , a5))

np.vsplit(a6 , 2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [173]:
np.vsplit(a6 , 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [174]:
np.vsplit(a6 , 6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]