**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [6]:
#Code here

# creating a null vector

a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [22]:
#Code here
import random

a = int(input("Enter 1st num : "))
b = int(input("Enter 2nd num : "))

# now generate the random array

c = (np.random.random((a , b)) * 100)
print(c)
d = np.floor(c)
print(d)

# calculate the average of the array

avg = np.mean(c)
print("Average is " , np.floor(avg))

Enter 1st num : 4
Enter 2nd num : 3
[[18.98329383 96.84979133 81.6974892 ]
 [19.14408465  9.6867393  60.63454466]
 [59.14065232 52.61821408 59.89485342]
 [23.87498667 69.62019575  5.27832708]]
[[18. 96. 81.]
 [19.  9. 60.]
 [59. 52. 59.]
 [23. 69.  5.]]
Average is  46.0


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [25]:
#Code here

import numpy as np

def border_array(a , b) :

  array = np.zeros((a , b))

  array[0 , :] = 1
  array[-1 , :] = 1
  array[: , 0] = 1
  array[: , -1] = 1

  return array


a = 4
b = 4

print(border_array(a , b))

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [24]:
import numpy as np

def create_border_array(a, b):
    array = np.zeros((a, b))

    # Set the border elements to 1
    array[0, :] = 1  # Top row
    array[-1, :] = 1  # Bottom row
    array[:, 0] = 1  # Left column
    array[:, -1] = 1  # Right column

    return array

# Example usage:
a = 4
b = 4

result_array = create_border_array(a, b)
print(result_array)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [27]:
#Code here

vector_array = np.arange(0 , 1 , 10)
print(vector_array)

# using np.arange we cant make it

[0]


In [29]:
vector_array = np.linspace(0 , 1 , 10)
print(vector_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [31]:
#Code here

a = np.identity(3)
print(a)

# we can only create 3*3 , 4*4 , 5*5
# not create 3*4 , 4*3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [48]:
#Code here

matrix = np.arange(5).reshape(5) + np.zeros((1, 5))

print(matrix)

[[0. 1. 2. 3. 4.]]


In [41]:
import numpy as np

matrix = np.tile(np.arange(5), (5, 1))

print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [51]:
#code here

import numpy as np

# Generate random integer vector of shape (10, 2)
random_vector = np.random.randint(1, 101, size=(10, 2))

# Given point coordinates
given_point = np.array([50, 50])


# Calculate distances
distances = np.linalg.norm(random_vector - given_point, axis=1).astype(int)

print(distances)


[50 50]
[55 37 29 16 51 53 61  5 33 44]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [52]:
#Code here
import numpy as np

array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)
index_100 = 100

if index_100 < total_elements:
    indices = np.unravel_index(index_100, array_shape)
    print(f"Index of the 100th element: {indices}")
else:
    print("The 100th element does not exist in the given array shape.")


Index of the 100th element: (1, 5, 4)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here

import numpy as np

# Input the space-separated numbers
numbers = input("Enter space-separated numbers: ")

# Split the input string into a list of numbers
number_list = numbers.split()

# Convert the list of strings to a NumPy array of floats
num_array = np.array(number_list, dtype=float)

# Reverse the NumPy array
reversed_array = np.flip(num_array)

# Print the reversed NumPy array
print(reversed_array)


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [54]:
#Code here

import numpy as np

# Input the NumPy array
array = np.array([0 , 1 , 2 , 3 , 4 , 5])

# Get the number of elements in the array
elements_count = array.size

# Print the number of elements
print("elements_count:", elements_count)


elements_count: 6


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [65]:
#code here

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

mean_row = np.mean(matrix, axis=1, keepdims=True)
result = matrix - mean_row

print(result)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

In [64]:
import numpy as np

array = np.array([[6, 3, 1, 5, 8],
                  [9, 4, 2, 7, 0]])

array[:, [0, 1]] = array[:, [1, 0]]

print(array)


[[3 6 1 5 8]
 [4 9 2 7 0]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [63]:
import numpy as np

array = np.array([6, 3, 1, 5, 8])

array[array % 2 != 0] = -1

print(array)


[ 6 -1 -1 -1  8]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [62]:
#Code here

import numpy as np

a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

result = np.maximum(a, b)

print(result)



[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [58]:
#Code here

arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8499, 8003, 2347, 7763, 2913],
       [9864,  451, 6198,  192, 1545],
       [1090, 9233, 9226, 9275, 7046],
       [7399, 2869, 3743, 6115, 3113],
       [7597, 9077, 3000, 7922, 9661],
       [3584, 1752, 1001, 5482, 5077],
       [ 125, 5118, 1710, 5326, 1592],
       [6706, 3604, 3788,  629, 7432]])

In [60]:
# Fetch Every alternate column of the array

print(arr1[ : , 0 : : 2])

[[8499 2347 2913]
 [9864 6198 1545]
 [1090 9226 7046]
 [7399 3743 3113]
 [7597 3000 9661]
 [3584 1001 5077]
 [ 125 1710 1592]
 [6706 3788 7432]]


In [61]:
norm = np.linalg.norm(arr1)
normalized_array = arr1 / norm

print(normalized_array)

[[0.23164878 0.2181298  0.06396984 0.21158836 0.07939674]
 [0.26885322 0.01229246 0.16893271 0.00523315 0.04211053]
 [0.02970904 0.25165468 0.25146389 0.25279944 0.1920458 ]
 [0.20166717 0.07819748 0.10201922 0.16667046 0.08484794]
 [0.20706386 0.24740275 0.08176801 0.21592206 0.26332025]
 [0.09768552 0.04775252 0.02728326 0.14941741 0.13837873]
 [0.003407   0.13949623 0.04660777 0.14516548 0.04339156]
 [0.18277876 0.09823064 0.10324574 0.01714403 0.20256662]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [56]:
#Code here

import numpy as np

def find_nth_largest(arr, n):
    sorted_arr = np.sort(arr)
    nth_largest = sorted_arr[-n]
    return nth_largest


In [57]:
arr = np.array([12, 34, 40, 7, 1, 0])
n = 3
result = find_nth_largest(arr, n)
print(result)  # Output: 12

n = 1
result = find_nth_largest(arr, n)
print(result)  # Output: 40


12
40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [55]:
#code here

import numpy as np

a = np.array([1, 2, 3])

repeated_a = np.repeat(a, len(a))
tiled_a = np.tile(a, len(a))

output = np.concatenate((repeated_a, tiled_a))

print(output)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
